services:
  dev-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: avertra
    networks:
      - avertra
networks:
  avertra:
